services:
  app:
    build: .
    depends_on:
    - db
    volumes:
      - .:/app
    command: ["python", "main.py"]

  db:
    image: postgres:13.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retail_sales
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    

